"""Statistics of `rng.stats` (validation/PROTOCOL.md) and the pass bounds the RNG tests apply to them.

The firmware reports, over `n` generated bytes read as one bit stream (each byte most significant bit first):
`ones` (set bits), `runs` (bit transitions + 1), `chisq` (the chi-square of the byte histogram against a uniform
distribution, 255 degrees of freedom, times 1000 rounded down and saturated at 2^32 - 1) and `crc` (zlib CRC-32).
`byte_stats` computes the same from the data, for the fake firmware and to check the firmware's definitions.

Bounds: monobit |ones - N/2| < 4 sigma with N = 8n bits and sigma = sqrt(N)/2 (NIST SP 800-22 2.1 at p ~ 6e-5); the
byte chi-square below 330.5 (the 0.999 quantile of chi-square with 255 degrees of freedom, p > 0.001); the runs
test of NIST SP 800-22 2.3 (prerequisite |pi - 1/2| < 2/sqrt(N)) with |runs - 2N pi (1 - pi)| below 4 of its
standard deviations 2 sqrt(N) pi (1 - pi).
"""

from __future__ import annotations

import math
import zlib
from dataclasses import dataclass

__all__ = [
    "CHI_SQUARE_LIMIT",
    "SIGMAS",
    "ByteStats",
    "byte_stats",
    "chi_square_ok",
    "chi_square_x1000",
    "failures",
    "monobit_ok",
    "runs_ok",
]

CHI_SQUARE_LIMIT = 330.5
SIGMAS = 4.0
_UINT32_MAX = 0xFFFFFFFF


@dataclass(frozen=True)
class ByteStats:
    n: int
    ones: int
    runs: int
    chisq_x1000: int
    crc: int


def chi_square_x1000(histogram: list[int], n: int) -> int:
    """sum((c - n/256)^2 / (n/256)) * 1000, in the firmware's integer arithmetic."""
    total = sum((count * 256 - n) ** 2 for count in histogram)
    return min(total * 1000 // (256 * n), _UINT32_MAX)


def byte_stats(data: bytes) -> ByteStats:
    histogram = [0] * 256
    for byte in data:
        histogram[byte] += 1
    bits = 8 * len(data)
    stream = int.from_bytes(data, "big")
    # Bit i of stream ^ (stream >> 1) is b(i) ^ b(i+1); the top one compares the first bit with nothing.
    transitions = ((stream ^ (stream >> 1)) & ((1 << max(bits - 1, 0)) - 1)).bit_count()
    return ByteStats(
        n=len(data),
        ones=stream.bit_count(),
        runs=transitions + 1,
        chisq_x1000=chi_square_x1000(histogram, len(data)) if data else 0,
        crc=zlib.crc32(data),
    )


def monobit_ok(n: int, ones: int, sigmas: float = SIGMAS) -> bool:
    bits = 8 * n
    return abs(ones - bits / 2) < sigmas * math.sqrt(bits) / 2


def chi_square_ok(chisq_x1000: int, limit: float = CHI_SQUARE_LIMIT) -> bool:
    return chisq_x1000 < limit * 1000


def runs_ok(n: int, ones: int, runs: int, sigmas: float = SIGMAS) -> bool:
    bits = 8 * n
    pi = ones / bits
    if abs(pi - 0.5) >= 2 / math.sqrt(bits):
        return False
    spread = 2 * math.sqrt(bits) * pi * (1 - pi)
    return abs(runs - 2 * bits * pi * (1 - pi)) < sigmas * spread


def failures(n: int, ones: int, runs: int, chisq_x1000: int) -> list[str]:
    """The names of the tests the counts fail (empty when random enough)."""
    failed = []
    if not monobit_ok(n, ones):
        failed.append(f"monobit: {ones} ones in {8 * n} bits")
    if not chi_square_ok(chisq_x1000):
        failed.append(f"chi-square: {chisq_x1000 / 1000} >= {CHI_SQUARE_LIMIT}")
    if not runs_ok(n, ones, runs):
        failed.append(f"runs: {runs} runs, {ones} ones in {8 * n} bits")
    return failed
