"""Random number generator through the `rng` group: `hal::SynchronousRandomDataGeneratorStm` (`variant=sync`),
`hal::RandomDataGeneratorStm` (`variant=async`, interrupt driven) and on STM32WB55
`hal::SynchronousSynchronizedRandomDataGeneratorStm` (`variant=hsem`: HSEM semaphore 0 around the read, HSI48 managed
by its `Hsi48Enabler` unless semaphore 5 is locked).

Every variant returns exactly the requested bytes, two reads differ, and 64 KiB pass the monobit, byte chi-square and
runs tests of `rngstats`. On STM32WB55 the synchronized variant keeps HSI48 (the RNG kernel clock) running when it was
on and switches it off again when it was off (B.9b), reads with semaphore 5 held (`lock5=1`), and leaves HSEM
semaphores 0 and 5 free (B.9). The firmware refuses what would hang or abort it: the plain variants while HSI48 is off,
the synchronized one while this core holds semaphore 0, while semaphore 5 is locked with HSI48 off, and while the
coordinated flash driver exists. No wiring.

Scenarios: features/rng.feature.
"""

from __future__ import annotations

import pytest
from ad3_waveforms_bench.terminal import FirmwareError
from pytest_bdd import given, parsers, scenario, then, when

from hal_st_validation import rngstats


@pytest.fixture
def rng_cfg(board_cfg):
    return board_cfg.param("rng")


def expect_reason(fw, line, reason):
    with pytest.raises(FirmwareError) as error:
        fw.terminal.command(line)
    assert error.value.reason == reason, line


def assert_semaphores_free(fw, rng_cfg):
    """`hsem.status` reads the semaphores without taking them (the hsem group of area-system, when built in)."""
    if not hasattr(fw, "hsem"):
        return
    for semaphore in rng_cfg["semaphores"]:
        response = fw.command("hsem.status", semaphore)
        assert response.as_int("locked") == 0, f"semaphore {semaphore}: {response.raw}"


def needs_clock_group(fw):
    if not hasattr(fw, "clock"):
        pytest.skip("needs the clock group (clock.hsi48, clock.info)")


def needs_hsem_group(fw):
    if not hasattr(fw, "hsem"):
        pytest.skip("needs the hsem group (hsem.take, hsem.release)")


@pytest.mark.board_params("variant", "rng.variants")
@pytest.mark.board_params("length", "rng.lengths")
@scenario("rng.feature", "A read returns the requested bytes")
def test_read_length(variant, length):
    pass


@pytest.mark.board_params("variant", "rng.variants")
@scenario("rng.feature", "Two reads differ")
def test_reads_differ(variant):
    pass


@pytest.mark.board_params("variant", "rng.variants")
@scenario("rng.feature", "The generated bytes pass the statistical tests")
def test_statistics(variant):
    pass


@pytest.mark.board_params("variant", "rng.variants")
@scenario("rng.feature", "The statistics of two generations differ")
def test_statistics_differ(variant):
    pass


@scenario("rng.feature", "The variants take turns")
def test_variants_take_turns():
    pass


@scenario("rng.feature", "The synchronized read keeps HSI48 running")
def test_hsem_keeps_hsi48():
    pass


@scenario("rng.feature", "The synchronized read switches HSI48 off again when it was off")
def test_hsem_restores_hsi48_off():
    pass


@scenario("rng.feature", "The synchronized read works with semaphore 5 locked")
def test_hsem_clock_locked():
    pass


@pytest.mark.parametrize("line", ["rng.read 4 lock5=1", "rng.read 4 variant=async lock5=1"])
@scenario("rng.feature", "Locking semaphore 5 needs the synchronized variant")
def test_clock_lock_needs_hsem_variant(line):
    pass


@scenario("rng.feature", "The firmware refuses the read with semaphore 5 locked and HSI48 off")
def test_clock_locked_needs_hsi48():
    pass


@scenario("rng.feature", "The plain variants need HSI48")
def test_plain_variants_need_hsi48():
    pass


@scenario("rng.feature", "The synchronized read refuses semaphore 0 held by this core")
def test_hsem_refuses_semaphore_0_of_this_core():
    pass


@scenario("rng.feature", "Semaphore 5 held by another process leaves HSI48 to the clock owner")
def test_hsem_semaphore_5_of_another_process():
    pass


@scenario("rng.feature", "The synchronized read excludes the coordinated flash driver")
def test_hsem_excludes_coordinated_flash():
    pass


@pytest.mark.parametrize(
    ("line", "reason"),
    [
        ("rng.read", "usage"),
        ("rng.read 4 5", "usage"),
        ("rng.read x", "usage"),
        ("rng.read 4 speed=1", "usage"),
        ("rng.read 0", "range"),
        ("rng.read 129", "range"),
        ("rng.read 4 variant=dma", "usage"),
        ("rng.read 4 lock5=2", "range"),
        ("rng.stats", "usage"),
        ("rng.stats 16 lock5=1", "usage"),
        ("rng.stats 15", "range"),
        ("rng.stats 65537", "range"),
        ("rng.stats 16 variant=x", "usage"),
    ],
)
@scenario("rng.feature", "Malformed and out-of-range commands are refused")
def test_errors(line, reason):
    pass


@pytest.mark.board_params("line", "rng.unsupported")
@scenario("rng.feature", "Commands the board does not support are refused")
def test_unsupported(line):
    pass


@given("the firmware has the clock group")
def has_clock_group(fw):
    needs_clock_group(fw)


@given("the firmware has the hsem group")
def has_hsem_group(fw):
    needs_hsem_group(fw)


@given("the firmware has the flash group")
def has_flash_group(fw):
    if not hasattr(fw, "flash"):
        pytest.skip("needs the flash group (flash.stack)")


@given("the statistics settings of the board file", target_fixture="settings")
def statistics_settings(rng_cfg):
    return rng_cfg["stats"]


@when("the length of bytes is read with the variant", target_fixture="read")
def read_length(fw, variant, length):
    return fw.rng.read(length, variant=variant)


@when(parsers.parse("{count:d} bytes are read twice with the variant"), target_fixture="reads")
def read_twice(fw, variant, count):
    return fw.rng.read(count, variant=variant), fw.rng.read(count, variant=variant)


@when(parsers.parse("{count:d} bytes are read with the hsem variant"), target_fixture="read")
def read_hsem(fw, count):
    return fw.rng.read(count, variant="hsem")


@when(parsers.parse("{count:d} bytes are read twice with the hsem variant and semaphore 5 locked"), target_fixture="reads")
def read_twice_clock_locked(fw, count):
    return fw.rng.read(count, variant="hsem", lock5=True), fw.rng.read(count, variant="hsem", lock5=True)


@when("the statistics of the settings length are generated with the variant within the settings timeout", target_fixture="stats")
def generate_statistics(fw, settings, variant):
    return fw.rng.stats(settings["length"], variant=variant, cmd_timeout=settings["timeout_s"])


@when(parsers.parse("the statistics of {count:d} bytes are generated twice with the variant"), target_fixture="stats_pair")
def generate_statistics_twice(fw, variant, count):
    return fw.rng.stats(count, variant=variant), fw.rng.stats(count, variant=variant)


@then("the read has the length of bytes")
def read_has_length(read, length):
    assert len(read.data) == length, read.raw


@then("the read reports the HSI48 state exactly when the variant is hsem")
def reports_hsi48_for_hsem(read, variant):
    assert (read.hsi48 is not None) == (variant == "hsem"), read.raw


@then("the two reads differ")
def reads_differ(reads):
    first, second = reads
    assert first.data != second.data


@then("the first read is neither all 0x00 nor all 0xFF")
def first_not_blank(reads):
    first = reads[0].data
    assert first not in (bytes(16), b"\xff" * 16)


@then("the statistics cover the settings length")
def statistics_cover_length(stats, settings):
    assert stats.n == settings["length"], stats.raw


@then("they pass the monobit, byte chi-square and runs bounds of rngstats")
def statistics_pass(stats):
    assert rngstats.failures(stats.n, stats.ones, stats.runs, stats.chisq_x1000) == [], stats.raw


@then("the generation took a positive time")
def generation_timed(stats):
    assert stats.us > 0, stats.raw


@then(parsers.parse("both cover {count:d} bytes"))
def both_cover(stats_pair, count):
    first, second = stats_pair
    assert first.n == second.n == count


@then("their CRCs differ")
def crcs_differ(stats_pair):
    first, second = stats_pair
    assert first.crc != second.crc


@then(
    parsers.parse("{count:d} bytes read with every variant of the board file in order and then in reverse order have {size:d} bytes each")
)
def variants_take_turns(fw, rng_cfg, count, size):
    variants = list(rng_cfg["variants"])
    for variant in variants + variants[::-1]:
        assert len(fw.rng.read(count, variant=variant).data) == size, variant


@then("the read reports HSI48 on")
def read_reports_hsi48_on(read):
    assert read.hsi48 == 1, read.raw


@then(parsers.parse("{count:d} bytes read with the {variant_name} variant have that many bytes"))
def read_with_variant_has_length(fw, count, variant_name):
    assert len(fw.rng.read(count, variant=variant_name).data) == count


@then(parsers.parse("{count:d} bytes read without a variant have that many bytes"))
def read_default_has_length(fw, count):
    assert len(fw.rng.read(count).data) == count


@then("HSI48 is on, if the firmware has the clock group")
def hsi48_on(fw):
    if hasattr(fw, "clock"):
        assert fw.clock.info().flags["hsi48"] == 1


@then("the semaphores of the board file are free, if the firmware has the hsem group")
def semaphores_free(fw, rng_cfg):
    assert_semaphores_free(fw, rng_cfg)


@then(
    parsers.parse(
        "with HSI48 switched off, {count:d} bytes read with the hsem variant report HSI48 off, have {size:d} bytes and leave HSI48 off, "
        "and HSI48 is switched on again even if that fails"
    )
)
def hsem_restores_hsi48_off(fw, count, size):
    fw.clock.hsi48(False)
    try:
        read = fw.rng.read(count, variant="hsem")
        assert read.hsi48 == 0, read.raw
        assert len(read.data) == size
        assert fw.clock.info().flags["hsi48"] == 0
    finally:
        fw.clock.hsi48(True)


@then(parsers.parse("{count:d} bytes read with the hsem variant report HSI48 on"))
def hsem_read_reports_hsi48_on(fw, count):
    assert fw.rng.read(count, variant="hsem").hsi48 == 1


@then("both reads report HSI48 on")
def both_report_hsi48_on(reads):
    first, second = reads
    assert first.hsi48 == second.hsi48 == 1, (first.raw, second.raw)


@then(parsers.parse('the command line fails with "{reason}"'))
def command_refused(fw, line, reason):
    expect_reason(fw, line, reason)


@then("the command line fails with the reason")
def command_refused_with_the_reason(fw, line, reason):
    expect_reason(fw, line, reason)


@then(parsers.parse('with HSI48 switched off, "{command}" fails with "{reason}", and HSI48 is switched on again even if that fails'))
def refused_with_hsi48_off(fw, command, reason):
    fw.clock.hsi48(False)
    try:
        expect_reason(fw, command, reason)
    finally:
        fw.clock.hsi48(True)


@then(
    parsers.parse(
        'with HSI48 switched off, the reads and statistics of the sync and async variants fail with "{reason}" and {count:d} bytes '
        "read with the hsem variant have {size:d} bytes, and HSI48 is switched on again even if that fails"
    )
)
def plain_variants_refused(fw, reason, count, size):
    fw.clock.hsi48(False)
    try:
        for line in ("rng.read 4", "rng.read 4 variant=async", "rng.stats 16", "rng.stats 16 variant=async"):
            expect_reason(fw, line, reason)
        assert len(fw.rng.read(count, variant="hsem").data) == size
    finally:
        fw.clock.hsi48(True)


@then(
    parsers.parse(
        "with semaphore 0 taken for process 1, the hsem variant's read of 4 bytes and statistics of 16 bytes fail with "
        '"{reason}", and the semaphore is released again even if that fails'
    )
)
def semaphore_0_refused(fw, reason):
    fw.hsem.take(0, procid=1)
    try:
        expect_reason(fw, "rng.read 4 variant=hsem", reason)
        expect_reason(fw, "rng.stats 16 variant=hsem", reason)
    finally:
        fw.hsem.release(0, procid=1)


@then(
    parsers.parse(
        "with semaphore 5 taken for process 1, {count:d} bytes read with the hsem variant report HSI48 on, the read with "
        'semaphore 5 locked fails with "{locked_reason}", and with HSI48 switched off the hsem variant\'s read fails with '
        '"{off_reason}", HSI48 switched on and the semaphore released again even if that fails'
    )
)
def semaphore_5_of_another_process(fw, count, locked_reason, off_reason):
    fw.hsem.take(5, procid=1)
    try:
        assert fw.rng.read(count, variant="hsem").hsi48 == 1
        expect_reason(fw, "rng.read 4 variant=hsem lock5=1", locked_reason)
        fw.clock.hsi48(False)
        try:
            expect_reason(fw, "rng.read 4 variant=hsem", off_reason)
        finally:
            fw.clock.hsi48(True)
    finally:
        fw.hsem.release(5, procid=1)


@then(
    parsers.parse(
        'with the flash stack "{state}", the hsem variant\'s read of {count:d} bytes fails with "{reason}" and {plain:d} bytes '
        'read without a variant have {size:d} bytes, and the flash stack is set to "{restored}" again even if that fails'
    )
)
def coordinated_flash_excludes_hsem(fw, state, count, reason, plain, size, restored):
    fw.flash.stack(state)
    try:
        expect_reason(fw, f"rng.read {count} variant=hsem", reason)
        assert len(fw.rng.read(plain).data) == size
    finally:
        fw.flash.stack(restored)
