Feature: Random number generator
  The random number generator through the `rng` group: `hal::SynchronousRandomDataGeneratorStm` (`variant=sync`),
  `hal::RandomDataGeneratorStm` (`variant=async`, interrupt driven) and on STM32WB55
  `hal::SynchronousSynchronizedRandomDataGeneratorStm` (`variant=hsem`: HSEM semaphore 0 around the read, HSI48
  managed by its `Hsi48Enabler` unless semaphore 5 is locked).

  Every variant returns exactly the requested bytes, two reads differ, and 64 KiB pass the monobit, byte chi-square
  and runs tests of `rngstats`. On STM32WB55 the synchronized variant keeps HSI48 (the RNG kernel clock) running when
  it was on and switches it off again when it was off (B.9b), reads with semaphore 5 held (`lock5=1`), and leaves
  HSEM semaphores 0 and 5 free (B.9). The firmware refuses what would hang or abort it: the plain variants while HSI48
  is off, the synchronized one while this core holds semaphore 0, while semaphore 5 is locked with HSI48 off, and
  while the coordinated flash driver exists. No wiring. The variants, the lengths, the statistics settings, the
  semaphores and the unsupported command lines are in tests.rng of the board file.

  Scenario: A read returns the requested bytes
    When the length of bytes is read with the variant
    Then the read has the length of bytes
    And the read reports the HSI48 state exactly when the variant is hsem

  Scenario: Two reads differ
    When 16 bytes are read twice with the variant
    Then the two reads differ
    And the first read is neither all 0x00 nor all 0xFF

  Scenario: The generated bytes pass the statistical tests
    64 KiB generated in 256-byte chunks pass the monobit, byte chi-square and runs bounds of `rngstats`.
    Given the statistics settings of the board file
    When the statistics of the settings length are generated with the variant within the settings timeout
    Then the statistics cover the settings length
    And they pass the monobit, byte chi-square and runs bounds of rngstats
    And the generation took a positive time

  Scenario: The statistics of two generations differ
    When the statistics of 256 bytes are generated twice with the variant
    Then both cover 256 bytes
    And their CRCs differ

  Scenario: The variants take turns
    Each variant enables and disables the RNG on its own; one after the other they all still deliver.
    Then 32 bytes read with every variant of the board file in order and then in reverse order have 32 bytes each

  @family:stm32wb55
  Scenario: The synchronized read keeps HSI48 running
    With HSI48 running (the default clock's RNG kernel clock) the synchronized read leaves it on, so the other
    variants still have their clock afterwards (B.9b).
    When 16 bytes are read with the hsem variant
    Then the read reports HSI48 on
    And 16 bytes read with the sync variant have that many bytes
    And 16 bytes read with the async variant have that many bytes
    And HSI48 is on, if the firmware has the clock group
    And the semaphores of the board file are free, if the firmware has the hsem group

  @family:stm32wb55
  Scenario: The synchronized read switches HSI48 off again when it was off
    With HSI48 off the synchronized read starts it for the read and switches it off again afterwards.
    Given the firmware has the clock group
    Then with HSI48 switched off, 16 bytes read with the hsem variant report HSI48 off, have 16 bytes and leave HSI48 off, and HSI48 is switched on again even if that fails
    And 16 bytes read with the hsem variant report HSI48 on
    And the semaphores of the board file are free, if the firmware has the hsem group

  @family:stm32wb55
  Scenario: The synchronized read works with semaphore 5 locked
    `lock5=1` holds semaphore 5 (clock configuration) around the read. With HSI48 on, the read works, leaves HSI48 on
    and frees both semaphores. The locked branch of `Hsi48Enabler` differs from the unlocked one only by its assert
    with HSI48 off, which the firmware refuses (test_clock_locked_needs_hsi48); the query itself is covered by
    test_hsem.py::test_query_takes_no_lock.
    When 16 bytes are read twice with the hsem variant and semaphore 5 locked
    Then both reads report HSI48 on
    And the two reads differ
    And the semaphores of the board file are free, if the firmware has the hsem group

  @family:stm32wb55
  Scenario: Locking semaphore 5 needs the synchronized variant
    `lock5` only applies to the synchronized variant.
    Then the command line fails with "usage"

  @family:stm32wb55
  Scenario: The firmware refuses the read with semaphore 5 locked and HSI48 off
    With semaphore 5 locked the driver asserts that HSI48 runs; the firmware refuses that read with HSI48 off.
    Given the firmware has the clock group
    Then with HSI48 switched off, "rng.read 4 variant=hsem lock5=1" fails with "failed", and HSI48 is switched on again even if that fails
    And the semaphores of the board file are free, if the firmware has the hsem group

  @family:stm32wb55
  Scenario: The plain variants need HSI48
    HSI48 is the RNG kernel clock (CLK48) and only `Hsi48Enabler` starts it: with HSI48 off the plain drivers would
    abort on the clock error or wait forever for data, so the firmware refuses them.
    Given the firmware has the clock group
    Then with HSI48 switched off, the reads and statistics of the sync and async variants fail with "failed" and 4 bytes read with the hsem variant have 4 bytes, and HSI48 is switched on again even if that fails
    And 4 bytes read without a variant have that many bytes

  @family:stm32wb55
  Scenario: The synchronized read refuses semaphore 0 held by this core
    The driver waits for semaphore 0 with the event loop blocked: held by `hsem.take` nothing could free it.
    Given the firmware has the hsem group
    Then with semaphore 0 taken for process 1, the hsem variant's read of 4 bytes and statistics of 16 bytes fail with "busy", and the semaphore is released again even if that fails
    And 4 bytes read with the hsem variant have that many bytes
    And the semaphores of the board file are free, if the firmware has the hsem group

  @family:stm32wb55
  Scenario: Semaphore 5 held by another process leaves HSI48 to the clock owner
    `IsLockedByCurrentCore` ignores the process: semaphore 5 taken by `hsem.take` leaves HSI48 to the clock owner,
    and with HSI48 off the firmware refuses the read the driver would assert on.
    Given the firmware has the hsem group
    And the firmware has the clock group
    Then with semaphore 5 taken for process 1, 4 bytes read with the hsem variant report HSI48 on, the read with semaphore 5 locked fails with "busy", and with HSI48 switched off the hsem variant's read fails with "failed", HSI48 switched on and the semaphore released again even if that fails
    And the semaphores of the board file are free, if the firmware has the hsem group

  @family:stm32wb55
  Scenario: The synchronized read excludes the coordinated flash driver
    `variant=hsem` shares HSEM 0 of `ResourceAllocation` with the coordinated flash driver and `hsem.lock`.
    Given the firmware has the flash group
    Then with the flash stack "starting", the hsem variant's read of 16 bytes fails with "busy" and 16 bytes read without a variant have 16 bytes, and the flash stack is set to "fus" again even if that fails
    And 16 bytes read with the hsem variant have that many bytes

  Scenario: Malformed and out-of-range commands are refused
    Then the command line fails with the reason

  Scenario: Commands the board does not support are refused
    Then the command line fails with "unsupported"
