name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  host_build_test_ubuntu:
    name: Host Build & Test (ubuntu-latest)
    uses: ./.github/workflows/build.yml
    with:
      build_type: host_ubuntu
      saveCache: ${{ github.event_name != 'pull_request' }}
    secrets: inherit

  host_build_test:
    name: Host Build & Test
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    uses: ./.github/workflows/build.yml
    with:
      build_type: host
      os: ${{ matrix.os }}
      saveCache: ${{ github.event_name != 'pull_request' }}
    secrets: inherit

  host_build_clang_msvc:
    name: Windows Host Build from Devcontainer
    uses: ./.github/workflows/build.yml
    with:
      build_type: host_clang_msvc
      saveCache: ${{ github.event_name != 'pull_request' }}
    secrets: inherit

  embedded_build:
    name: Embedded Build
    needs: [host_build_test_ubuntu]
    strategy:
      matrix:
        configuration: ["RelWithDebInfo"]
        gcc: ["10.3-2021.10"]
        target: [
          "stm32wb55", 
          "stm32wba52", 
          "stm32g070", 
          "stm32g431", 
          "stm32f407", 
          "stm32f429", 
          "stm32f746", 
          "stm32f767", 
          "stm32h563", 
          "stm32h573"
        ]
        include:
          - gcc: "8-2019-q3"
            configuration: "RelWithDebInfo"
            target: "stm32f767"
          - gcc: "9-2020-q2"
            configuration: "RelWithDebInfo"
            target: "stm32f767"
    uses: ./.github/workflows/build.yml
    with:
      build_type: embedded
      configuration: ${{ matrix.configuration }}
      gcc_version: ${{ matrix.gcc }}
      target: ${{ matrix.target }}
      saveCache: ${{ github.event_name != 'pull_request' }}
    secrets: inherit